In [239]:

try:
    import serial
    import numpy as np
    from matplotlib import pyplot as plt
except:
    %pip install pyserial
    %pip install numpy
    %pip install matplotlib
    import serial
    import numpy as np
    from matplotlib import pyplot as plt

In [240]:
import random as rd
import time

In [241]:
def print_matrix(X):
  cmp = len(str(X[0][0]))
  for i in range(X.shape[0]):
    for j in range(X.shape[1]):
      if(X[i][j] ==0):
        print(f'0'*cmp,end='')
      else:
        print(f'{X[i][j]:d}',end='')
    print()

In [279]:
def create_matrix(Din,DigitosPorSimbolo):
  #Din = 8 #Diminsão das matrizes
  #DigitosPorSimbolo = 1 #digitos por elementos das matrizes
  Ain = np.zeros((Din,Din),dtype=int)
  Bin = np.zeros((Din,Din),dtype=int)
  for i in range(Din):
    for j in range(Din):
      Ain[i][j] = rd.randint(0*1*(DigitosPorSimbolo-1),1*1**(DigitosPorSimbolo-1))
      Bin[i][j] = rd.randint(0*1*(DigitosPorSimbolo-1),1*1**(DigitosPorSimbolo-1))
  return [Ain,Bin]

In [243]:
#Preprocessamendo das matrizes
def shiftMatrixSystolic(X1:np.ndarray,X2:np.ndarray):
  Y1 = np.zeros((X1.shape[0],2*X1.shape[0]-1),dtype=int)
  Y2 = np.zeros((X2.shape[0],2*X2.shape[0]-1),dtype=int)
  for i in range(X1.shape[0]):
    for j in range(X1.shape[1]):
      if(j < X1.shape[1]):
        Y1[i][j+X1.shape[0]-i-1] = X1[i][j]
        Y2[i][j+X1.shape[0]-i-1] = X2[j][i]
        #Y2[i+j][j] = X2[i][j] #Transposta do segundo operando
        #Y2[i+j][i] = X2[i][j]
      else:
        Y1[i][j] = 0
        Y2[i][j] = 0
  return [Y1,Y2]


In [249]:
#plt.subplot(1,2,1)
#plt.imshow(Ain)
#plt.subplot(1,2,2)
#plt.imshow(Bin)
#plt.show()


In [250]:
#plt.subplot(1,2,1)
#plt.imshow(Ms[0])
#plt.subplot(1,2,2)#
#plt.imshow(Ms[1])
#plt.show()

In [290]:
def send_matrix(X,input,flag):
  file = open(f"teste{input}.txt","+w")

  if(flag):
    s = serial.Serial()
    s.port = "/dev/ttyUSB1"
    s.baudrate = 115200
    s.bytesize = 8
    s.open()
  Fs =10000
  cmp = len(str(X[0][0]))
  file.write(f"assign {input}[{0}] = "+"8'b"+str(11111111)+";\n")
  for i in range(X.shape[1]):
    strbin = ''
    for j in range(X.shape[0]):
      if(X[j][i] ==0):
        strbin+=str(X[j][i])
      else:
        strbin+=str(X[j][i])
    print('0b'+strbin,i)
    print(int('0b'+strbin,2))
    file.write(f"assign {input}[{i+1}] = "+"8'b"+strbin+";\n")
    if(flag):
      s.write(bytearray([int('0b'+strbin,2)]))
      time.sleep(1/Fs)  
  if(flag):
    s.write(bytearray([255]))
    s.close()  
  file.close()
  

In [282]:
M = create_matrix(Din = 8, DigitosPorSimbolo=1)
M[1]

array([[0, 0, 1, 1, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 1],
       [0, 1, 0, 0, 1, 1, 1, 0],
       [1, 1, 1, 0, 0, 1, 1, 1],
       [0, 1, 0, 0, 0, 0, 1, 1]])

In [285]:
M[0]@M[1]

array([[1, 2, 3, 2, 2, 2, 1, 1],
       [1, 2, 1, 0, 0, 1, 2, 2],
       [1, 3, 1, 0, 0, 1, 2, 1],
       [1, 3, 1, 1, 2, 2, 3, 3],
       [1, 3, 1, 2, 3, 2, 3, 3],
       [0, 1, 1, 1, 1, 0, 1, 1],
       [1, 3, 2, 2, 2, 2, 2, 3],
       [1, 2, 2, 2, 3, 2, 2, 1]])

M_p = shiftMatrixSystolic(M[0],M[1])

In [293]:
for i in range(1):
    print("----------------------",i,"--------------------------")
    M_p = shiftMatrixSystolic(M[0],M[1])
    #Bin = M[1]
    send_matrix(M_p[0],"IMPUT_A",0)
    send_matrix(M_p[1],"IMPUT_B",0)
    
    break
    time.sleep(10)

---------------------- 0 --------------------------
0b00000001 0
1
0b00000000 1
0
0b00000101 2
5
0b00000010 3
2
0b00000010 4
2
0b00001011 5
11
0b00100001 6
33
0b10001010 7
138
0b00111010 8
58
0b10011100 9
156
0b10011000 10
152
0b00010000 11
16
0b01100000 12
96
0b11000000 13
192
0b00000000 14
0
0b00000000 0
0
0b00000000 1
0
0b00000010 2
2
0b00001000 3
8
0b00010001 4
17
0b00101100 5
44
0b00010011 6
19
0b01001111 7
79
0b10111110 8
190
0b01000000 9
64
0b00000000 10
0
0b01100000 11
96
0b01000000 12
64
0b11000000 13
192
0b00000000 14
0


In [292]:
M[0]@M[1]

array([[1, 2, 3, 2, 2, 2, 1, 1],
       [1, 2, 1, 0, 0, 1, 2, 2],
       [1, 3, 1, 0, 0, 1, 2, 1],
       [1, 3, 1, 1, 2, 2, 3, 3],
       [1, 3, 1, 2, 3, 2, 3, 3],
       [0, 1, 1, 1, 1, 0, 1, 1],
       [1, 3, 2, 2, 2, 2, 2, 3],
       [1, 2, 2, 2, 3, 2, 2, 1]])

In [254]:
M_p = shiftMatrixSystolic(M[0],M[0])
M_p[0],M_p[1]

(array([[0, 0, 0, 0, 0, 0, 0, 5, 8, 3, 5, 4, 3, 7, 5],
        [0, 0, 0, 0, 0, 0, 7, 0, 8, 7, 1, 9, 4, 8, 0],
        [0, 0, 0, 0, 0, 2, 8, 1, 9, 3, 7, 2, 7, 0, 0],
        [0, 0, 0, 0, 2, 5, 1, 4, 4, 0, 5, 6, 0, 0, 0],
        [0, 0, 0, 3, 6, 5, 9, 5, 0, 4, 6, 0, 0, 0, 0],
        [0, 0, 0, 5, 2, 4, 5, 9, 9, 2, 0, 0, 0, 0, 0],
        [0, 4, 4, 4, 9, 4, 7, 7, 5, 0, 0, 0, 0, 0, 0],
        [1, 6, 3, 9, 4, 4, 7, 2, 0, 0, 0, 0, 0, 0, 0]]),
 array([[0, 0, 0, 0, 0, 0, 0, 5, 7, 2, 2, 3, 0, 4, 1],
        [0, 0, 0, 0, 0, 0, 8, 0, 8, 5, 6, 5, 4, 6, 0],
        [0, 0, 0, 0, 0, 3, 8, 1, 1, 5, 2, 4, 3, 0, 0],
        [0, 0, 0, 0, 5, 7, 9, 4, 9, 4, 9, 9, 0, 0, 0],
        [0, 0, 0, 4, 1, 3, 4, 5, 5, 4, 4, 0, 0, 0, 0],
        [0, 0, 3, 9, 7, 0, 0, 9, 7, 4, 0, 0, 0, 0, 0],
        [0, 7, 4, 2, 5, 4, 9, 7, 7, 0, 0, 0, 0, 0, 0],
        [5, 8, 7, 6, 6, 2, 5, 2, 0, 0, 0, 0, 0, 0, 0]]))

In [255]:
def send_matrix(X,input,flag):
  file = open(f"teste{input}.txt","+w")
  file.write(f"assign {input}[{0}] = "+"32'"+"h"+str("ffffffff")+";\n")
  for i in range(X.shape[1]):
    strbin = 0
    for j in range(X.shape[0]):
        strbin+= int(X[j][i]*pow(10,X.shape[0]-1-j))
    print(f'{strbin:08d}',i)
   # print(int('0b'+strbin,2))
    file.write(f"assign {input}[{i+1}] = "+"32'"+"h"+f'{strbin:08d}'+";\n")
  #file.close()

for i in range(1):
    print("----------------------",i,"--------------------------")
    M_p = shiftMatrixSystolic(M[0],M[1])
    #Bin = M[1]
    send_matrix(M_p[0],"IMPUT_A",0)
    send_matrix(M_p[1],"IMPUT_B",0)
    
    break
    time.sleep(10)

#send_matrix(Bin)

---------------------- 0 --------------------------
00000001 0
00000046 1
00000043 2
00003549 3
00026294 4
00255444 5
07819577 6
50145972 7
88940950 8
37304200 9
51756000 10
49260000 11
34700000 12
78000000 13
50000000 14
00000001 0
00000030 1
00000604 2
00005070 3
00041163 4
00093455 5
00174373 6
91446998 7
36313340 8
58702300 9
53526000 10
79370000 11
39100000 12
91000000 13
40000000 14


In [266]:
M[0]@M[1]

array([[229, 173, 104, 186, 139, 128, 190, 105],
       [240, 232, 125, 177, 176, 198, 255, 163],
       [180, 183, 108, 179, 142, 148, 177, 112],
       [155, 106,  70, 132, 104,  74, 126,  81],
       [210, 165, 106, 192, 146, 104, 183,  98],
       [196, 228, 134, 112, 114, 147, 215, 111],
       [245, 243, 136, 169, 161, 175, 246, 128],
       [198, 209, 116, 147, 118, 120, 197,  82]])

In [257]:
shiftMatrixSystolic(M[0],M[1])

[array([[0, 0, 0, 0, 0, 0, 0, 5, 8, 3, 5, 4, 3, 7, 5],
        [0, 0, 0, 0, 0, 0, 7, 0, 8, 7, 1, 9, 4, 8, 0],
        [0, 0, 0, 0, 0, 2, 8, 1, 9, 3, 7, 2, 7, 0, 0],
        [0, 0, 0, 0, 2, 5, 1, 4, 4, 0, 5, 6, 0, 0, 0],
        [0, 0, 0, 3, 6, 5, 9, 5, 0, 4, 6, 0, 0, 0, 0],
        [0, 0, 0, 5, 2, 4, 5, 9, 9, 2, 0, 0, 0, 0, 0],
        [0, 4, 4, 4, 9, 4, 7, 7, 5, 0, 0, 0, 0, 0, 0],
        [1, 6, 3, 9, 4, 4, 7, 2, 0, 0, 0, 0, 0, 0, 0]]),
 array([[0, 0, 0, 0, 0, 0, 0, 9, 3, 5, 5, 7, 3, 9, 4],
        [0, 0, 0, 0, 0, 0, 0, 1, 6, 8, 3, 9, 9, 1, 0],
        [0, 0, 0, 0, 0, 0, 1, 4, 3, 7, 5, 3, 1, 0, 0],
        [0, 0, 0, 0, 4, 9, 7, 4, 1, 0, 2, 7, 0, 0, 0],
        [0, 0, 0, 5, 1, 3, 4, 6, 3, 2, 6, 0, 0, 0, 0],
        [0, 0, 6, 0, 1, 4, 3, 9, 3, 3, 0, 0, 0, 0, 0],
        [0, 3, 0, 7, 6, 5, 7, 9, 4, 0, 0, 0, 0, 0, 0],
        [1, 0, 4, 0, 3, 5, 3, 8, 0, 0, 0, 0, 0, 0, 0]])]

In [258]:
M[0]@M[1]

array([[229, 173, 104, 186, 139, 128, 190, 105],
       [240, 232, 125, 177, 176, 198, 255, 163],
       [180, 183, 108, 179, 142, 148, 177, 112],
       [155, 106,  70, 132, 104,  74, 126,  81],
       [210, 165, 106, 192, 146, 104, 183,  98],
       [196, 228, 134, 112, 114, 147, 215, 111],
       [245, 243, 136, 169, 161, 175, 246, 128],
       [198, 209, 116, 147, 118, 120, 197,  82]])

In [259]:

for i in range(1):
    print("----------------------",i,"--------------------------")
    M_p = shiftMatrixSystolic(M[0],M[1])
    #Bin = M[1]
    send_matrix(M_p[0],"IMPUT_A",0)
    send_matrix(M_p[1],"IMPUT_B",0)
    
    break
    time.sleep(10)

#send_matrix(Bin)

---------------------- 0 --------------------------
00000001 0
00000046 1
00000043 2
00003549 3
00026294 4
00255444 5
07819577 6
50145972 7
88940950 8
37304200 9
51756000 10
49260000 11
34700000 12
78000000 13
50000000 14
00000001 0
00000030 1
00000604 2
00005070 3
00041163 4
00093455 5
00174373 6
91446998 7
36313340 8
58702300 9
53526000 10
79370000 11
39100000 12
91000000 13
40000000 14


In [260]:
M[0]

array([[5, 8, 3, 5, 4, 3, 7, 5],
       [7, 0, 8, 7, 1, 9, 4, 8],
       [2, 8, 1, 9, 3, 7, 2, 7],
       [2, 5, 1, 4, 4, 0, 5, 6],
       [3, 6, 5, 9, 5, 0, 4, 6],
       [0, 5, 2, 4, 5, 9, 9, 2],
       [4, 4, 4, 9, 4, 7, 7, 5],
       [1, 6, 3, 9, 4, 4, 7, 2]])

In [261]:
M[1]

array([[9, 0, 0, 4, 5, 6, 3, 1],
       [3, 1, 1, 9, 1, 0, 0, 0],
       [5, 6, 4, 7, 3, 1, 7, 4],
       [5, 8, 3, 4, 4, 4, 6, 0],
       [7, 3, 7, 1, 6, 3, 5, 3],
       [3, 9, 5, 0, 3, 9, 7, 5],
       [9, 9, 3, 2, 2, 3, 9, 3],
       [4, 1, 1, 7, 6, 3, 4, 8]])

In [262]:
M[0]@M[1]

array([[229, 173, 104, 186, 139, 128, 190, 105],
       [240, 232, 125, 177, 176, 198, 255, 163],
       [180, 183, 108, 179, 142, 148, 177, 112],
       [155, 106,  70, 132, 104,  74, 126,  81],
       [210, 165, 106, 192, 146, 104, 183,  98],
       [196, 228, 134, 112, 114, 147, 215, 111],
       [245, 243, 136, 169, 161, 175, 246, 128],
       [198, 209, 116, 147, 118, 120, 197,  82]])

In [263]:
s = serial.Serial()

s.port = "/dev/ttyUSB1"
s.baudrate = 115200
s.bytesize = 8
s.close()
s.open()

In [264]:
i =1
s.write(bytearray([int(i)]))


1

In [265]:
serial.Serial()

Serial<id=0x7f02c5438850, open=False>(port=None, baudrate=9600, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False)